specVersion: 0.0.1
description: ''
repository: https://github.com/nasko25/substrate-exercises
schema: ./schema.graphql
network:
  # the endpoint has to be a full archive node
  endpoint: wss://polkadot.api.onfinality.io/public-ws    # this endpoint determines the blockchain subquery will query from
  # endpoint: wss://kusama.api.onfinality.io/public-ws    # this is the kusama endpoint
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
  # Dictionaries are useful when not all data from all blocks needs to be indexed.
  # For more information: https://doc.subquery.network/tutorials_examples/dictionary/#
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1     # determines the start block
    mapping:
      handlers:
        # - handler: handleBlock
        #   kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
        #     method: Deposit
            # focus on balances.Transfer
            method: Transfer    # grab only the 'Transfer' information from the blocks
                                # the other events can be found on each block's
                                # events page. For example: https://polkadot.subscan.io/block/7038273?tab=event
        # - handler: handleCall
        #   kind: substrate/CallHandler
